//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace GneissBooks.Saft;


using System.Xml.Serialization;


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IsNullable = false)]
public partial class AuditFile
{

    /// <remarks/>
    public AuditFileHeader Header;

    /// <remarks/>
    public AuditFileMasterFiles MasterFiles;

    /// <remarks/>
    public AuditFileGeneralLedgerEntries GeneralLedgerEntries;

    /// <remarks/>
    public AuditFileSourceDocuments SourceDocuments;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileHeader : HeaderStructure
{

    /// <remarks/>
    public AuditFileHeaderTaxAccountingBasis TaxAccountingBasis;

    /// <remarks/>
    public string TaxEntity;

    /// <remarks/>
    public string UserID;

    /// <remarks/>
    public CompanyStructure AuditFileSender;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum AuditFileHeaderTaxAccountingBasis
{

    /// <remarks/>
    A,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyHeaderStructure))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class CompanyStructure
{

    /// <remarks/>
    public string RegistrationNumber;

    /// <remarks/>
    public string Name;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Address")]
    public AddressStructure[] Address;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Contact")]
    public ContactInformationStructure[] Contact;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxRegistration")]
    public TaxIDStructure[] TaxRegistration;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BankAccount")]
    public BankAccountStructure[] BankAccount;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AddressStructure
{

    /// <remarks/>
    public string StreetName;

    /// <remarks/>
    public string Number;

    /// <remarks/>
    public string AdditionalAddressDetail;

    /// <remarks/>
    public string Building;

    /// <remarks/>
    public string City;

    /// <remarks/>
    public string PostalCode;

    /// <remarks/>
    public string Region;

    /// <remarks/>
    public string Country;

    /// <remarks/>
    public AddressStructureAddressType AddressType;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddressTypeSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum AddressStructureAddressType
{

    /// <remarks/>
    StreetAddress,

    /// <remarks/>
    PostalAddress,

    /// <remarks/>
    BillingAddress,

    /// <remarks/>
    ShipToAddress,

    /// <remarks/>
    ShipFromAddress,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class ShippingPointStructure
{

    /// <remarks/>
    public string DeliveryID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime DeliveryDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryDateSpecified;

    /// <remarks/>
    public string WarehouseID;

    /// <remarks/>
    public string LocationID;

    /// <remarks/>
    public string UCR;

    /// <remarks/>
    public AddressStructure Address;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructure
{

    /// <remarks/>
    public string InvoiceNo;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerInfo", typeof(InvoiceStructureCustomerInfo))]
    [System.Xml.Serialization.XmlElementAttribute("SupplierInfo", typeof(InvoiceStructureSupplierInfo))]
    public object Item;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    public string BranchStoreNumber;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string Period;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string PeriodYear;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime InvoiceDate;

    /// <remarks/>
    public string InvoiceType;

    /// <remarks/>
    public ShippingPointStructure ShipTo;

    /// <remarks/>
    public ShippingPointStructure ShipFrom;

    /// <remarks/>
    public string PaymentTerms;

    /// <remarks/>
    public string SelfBillingIndicator;

    /// <remarks/>
    public string SourceID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime GLPostingDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GLPostingDateSpecified;

    /// <remarks/>
    public string BatchID;

    /// <remarks/>
    public string SystemID;

    /// <remarks/>
    public string TransactionID;

    /// <remarks/>
    public string ReceiptNumbers;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public InvoiceStructureLine[] Line;

    /// <remarks/>
    public InvoiceStructureSettlement Settlement;

    /// <remarks/>
    public InvoiceStructureDocumentTotals DocumentTotals;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureCustomerInfo
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerID", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Name", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType5 ItemElementName;

    /// <remarks/>
    public AddressStructure BillingAddress;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemChoiceType5
{

    /// <remarks/>
    CustomerID,

    /// <remarks/>
    Name,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureSupplierInfo
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SupplierID", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType6 ItemElementName;

    /// <remarks/>
    public AddressStructure BillingAddress;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemChoiceType6
{

    /// <remarks/>
    Name,

    /// <remarks/>
    SupplierID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureLine
{

    /// <remarks/>
    public string LineNumber;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Analysis")]
    public AnalysisStructure[] Analysis;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrderReferences")]
    public InvoiceStructureLineOrderReferences[] OrderReferences;

    /// <remarks/>
    public ShippingPointStructure ShipTo;

    /// <remarks/>
    public ShippingPointStructure ShipFrom;

    /// <remarks/>
    public string GoodsServicesID;

    /// <remarks/>
    public string ProductCode;

    /// <remarks/>
    public string ProductDescription;

    /// <remarks/>
    public InvoiceStructureLineDelivery Delivery;

    /// <remarks/>
    public decimal Quantity;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QuantitySpecified;

    /// <remarks/>
    public string InvoiceUOM;

    /// <remarks/>
    public decimal UOMToUOMBaseConversionFactor;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UOMToUOMBaseConversionFactorSpecified;

    /// <remarks/>
    public decimal UnitPrice;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime TaxPointDate;

    /// <remarks/>
    public InvoiceStructureLineReferences References;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    public AmountStructure InvoiceLineAmount;

    /// <remarks/>
    public InvoiceStructureLineDebitCreditIndicator DebitCreditIndicator;

    /// <remarks/>
    public AmountStructure ShippingCostsAmount;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxInformation")]
    public TaxInformationStructure[] TaxInformation;
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AnalysisPartyInfoStructure))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AnalysisStructure
{

    /// <remarks/>
    public string AnalysisType;

    /// <remarks/>
    public string AnalysisID;

    /// <remarks/>
    public AmountStructure AnalysisAmount;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AmountStructure
{

    /// <remarks/>
    public decimal Amount;

    /// <remarks/>
    public string CurrencyCode;

    /// <remarks/>
    public decimal CurrencyAmount;

    /// <remarks/>
    public decimal ExchangeRate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExchangeRateSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AnalysisPartyInfoStructure : AnalysisStructure
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureLineOrderReferences
{

    /// <remarks/>
    public string OriginatingON;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime OrderDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderDateSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureLineDelivery
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeliveryDate", typeof(System.DateTime), DataType = "date")]
    [System.Xml.Serialization.XmlElementAttribute("DeliveryPeriod", typeof(InvoiceStructureLineDeliveryDeliveryPeriod))]
    [System.Xml.Serialization.XmlElementAttribute("MovementReference", typeof(string))]
    public object[] Items;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureLineDeliveryDeliveryPeriod
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime FromDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime ToDate;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureLineReferences
{

    /// <remarks/>
    public InvoiceStructureLineReferencesCreditNote CreditNote;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureLineReferencesCreditNote
{

    /// <remarks/>
    public string Reference;

    /// <remarks/>
    public string Reason;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum InvoiceStructureLineDebitCreditIndicator
{

    /// <remarks/>
    D,

    /// <remarks/>
    C,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class TaxInformationStructure
{

    /// <remarks/>
    public TaxInformationStructureTaxType TaxType;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxTypeSpecified;

    /// <remarks/>
    public string TaxCode;

    /// <remarks/>
    public decimal TaxPercentage;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxPercentageSpecified;

    /// <remarks/>
    public string Country;

    /// <remarks/>
    public decimal TaxBase;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxBaseSpecified;

    /// <remarks/>
    public string TaxBaseDescription;

    /// <remarks/>
    public AmountStructure TaxAmount;

    /// <remarks/>
    public string TaxExemptionReason;

    /// <remarks/>
    public string TaxDeclarationPeriod;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum TaxInformationStructureTaxType
{

    /// <remarks/>
    MVA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureSettlement
{

    /// <remarks/>
    public string SettlementDiscount;

    /// <remarks/>
    public AmountStructure SettlementAmount;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime SettlementDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SettlementDateSpecified;

    /// <remarks/>
    public string PaymentMechanism;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class InvoiceStructureDocumentTotals
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxInformationTotals")]
    public TaxInformationStructure[] TaxInformationTotals;

    /// <remarks/>
    public decimal ShippingCostsAmountTotal;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShippingCostsAmountTotalSpecified;

    /// <remarks/>
    public decimal NetTotal;

    /// <remarks/>
    public decimal GrossTotal;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class PartyInfoStructure
{

    /// <remarks/>
    public PartyInfoStructurePaymentTerms PaymentTerms;

    /// <remarks/>
    public string NaceCode;

    /// <remarks/>
    public string CurrencyCode;

    /// <remarks/>
    public PartyInfoStructureType Type;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified;

    /// <remarks/>
    public PartyInfoStructureStatus Status;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Analysis")]
    public AnalysisPartyInfoStructure[] Analysis;

    /// <remarks/>
    public string Notes;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class PartyInfoStructurePaymentTerms
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string Days;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string Months;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CashDiscountDays;

    /// <remarks/>
    public decimal CashDiscountRate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CashDiscountRateSpecified;

    /// <remarks/>
    public bool FreeBillingMonth;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FreeBillingMonthSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum PartyInfoStructureType
{

    /// <remarks/>
    Private,

    /// <remarks/>
    Company,

    /// <remarks/>
    Government,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum PartyInfoStructureStatus
{

    /// <remarks/>
    Active,

    /// <remarks/>
    Observation,

    /// <remarks/>
    Passive,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class SelectionCriteriaStructure
{

    /// <remarks/>
    public string TaxReportingJurisdiction;

    /// <remarks/>
    public string CompanyEntity;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PeriodEnd", typeof(string), DataType = "nonNegativeInteger")]
    [System.Xml.Serialization.XmlElementAttribute("PeriodEndYear", typeof(string), DataType = "nonNegativeInteger")]
    [System.Xml.Serialization.XmlElementAttribute("PeriodStart", typeof(string), DataType = "nonNegativeInteger")]
    [System.Xml.Serialization.XmlElementAttribute("PeriodStartYear", typeof(string), DataType = "nonNegativeInteger")]
    [System.Xml.Serialization.XmlElementAttribute("SelectionEndDate", typeof(System.DateTime), DataType = "date")]
    [System.Xml.Serialization.XmlElementAttribute("SelectionStartDate", typeof(System.DateTime), DataType = "date")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName;

    /// <remarks/>
    public string DocumentType;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OtherCriteria")]
    public string[] OtherCriteria;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemsChoiceType1
{

    /// <remarks/>
    PeriodEnd,

    /// <remarks/>
    PeriodEndYear,

    /// <remarks/>
    PeriodStart,

    /// <remarks/>
    PeriodStartYear,

    /// <remarks/>
    SelectionEndDate,

    /// <remarks/>
    SelectionStartDate,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class BankAccountStructure
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BankAccountName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("BankAccountNumber", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IBANNumber", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SortCode", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName;

    /// <remarks/>
    public string BIC;

    /// <remarks/>
    public string CurrencyCode;

    /// <remarks/>
    public string GeneralLedgerAccountID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemsChoiceType
{

    /// <remarks/>
    BankAccountName,

    /// <remarks/>
    BankAccountNumber,

    /// <remarks/>
    IBANNumber,

    /// <remarks/>
    SortCode,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class TaxIDStructure
{

    /// <remarks/>
    public string TaxRegistrationNumber;

    /// <remarks/>
    public string TaxType;

    /// <remarks/>
    public string TaxNumber;

    /// <remarks/>
    public TaxIDStructureTaxAuthority TaxAuthority;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxAuthoritySpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime TaxVerificationDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxVerificationDateSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum TaxIDStructureTaxAuthority
{

    /// <remarks/>
    Skatteetaten,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class PersonNameStructure
{

    /// <remarks/>
    public string Title;

    /// <remarks/>
    public string FirstName;

    /// <remarks/>
    public string Initials;

    /// <remarks/>
    public string LastNamePrefix;

    /// <remarks/>
    public string LastName;

    /// <remarks/>
    public string BirthName;

    /// <remarks/>
    public string Salutation;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OtherTitles")]
    public string[] OtherTitles;
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactHeaderStructure))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class ContactInformationStructure
{

    /// <remarks/>
    public PersonNameStructure ContactPerson;

    /// <remarks/>
    public string Telephone;

    /// <remarks/>
    public string Fax;

    /// <remarks/>
    public string Email;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
    public string Website;

    /// <remarks/>
    public string MobilePhone;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class ContactHeaderStructure : ContactInformationStructure
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class HeaderStructure
{

    /// <remarks/>
    public string AuditFileVersion;

    /// <remarks/>
    public string AuditFileCountry;

    /// <remarks/>
    public string AuditFileRegion;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime AuditFileDateCreated;

    /// <remarks/>
    public string SoftwareCompanyName;

    /// <remarks/>
    public string SoftwareID;

    /// <remarks/>
    public string SoftwareVersion;

    /// <remarks/>
    public CompanyHeaderStructure Company;

    /// <remarks/>
    public string DefaultCurrencyCode;

    /// <remarks/>
    public SelectionCriteriaStructure SelectionCriteria;

    /// <remarks/>
    public string HeaderComment;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class CompanyHeaderStructure : CompanyStructure
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFiles
{

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Account", IsNullable = false)]
    public AuditFileMasterFilesAccount[] GeneralLedgerAccounts;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Taxonomy", IsNullable = false)]
    public AuditFileMasterFilesTaxonomy[] Taxonomies;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Customer", IsNullable = false)]
    public AuditFileMasterFilesCustomer[] Customers;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Supplier", IsNullable = false)]
    public AuditFileMasterFilesSupplier[] Suppliers;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TaxTableEntry", IsNullable = false)]
    public AuditFileMasterFilesTaxTableEntry[] TaxTable;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("UOMTableEntry", IsNullable = false)]
    public AuditFileMasterFilesUOMTableEntry[] UOMTable;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AnalysisTypeTableEntry", IsNullable = false)]
    public AuditFileMasterFilesAnalysisTypeTableEntry[] AnalysisTypeTable;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("MovementTypeTableEntry", IsNullable = false)]
    public AuditFileMasterFilesMovementTypeTableEntry[] MovementTypeTable;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable = false)]
    public AuditFileMasterFilesProduct[] Products;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PhysicalStockEntry", IsNullable = false)]
    public AuditFileMasterFilesPhysicalStockEntry[] PhysicalStock;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Owner", IsNullable = false)]
    public AuditFileMasterFilesOwner[] Owners;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Asset", IsNullable = false)]
    public AuditFileMasterFilesAsset[] Assets;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesAccount
{

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    public string AccountDescription;

    /// <remarks/>
    public string StandardAccountID;

    /// <remarks/>
    public string GroupingCategory;

    /// <remarks/>
    public string GroupingCode;

    /// <remarks/>
    public AuditFileMasterFilesAccountAccountType AccountType;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime AccountCreationDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccountCreationDateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OpeningCreditBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("OpeningDebitBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClosingCreditBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("ClosingDebitBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
    public decimal Item1;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public Item1ChoiceType Item1ElementName;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum AuditFileMasterFilesAccountAccountType
{

    /// <remarks/>
    GL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemChoiceType
{

    /// <remarks/>
    OpeningCreditBalance,

    /// <remarks/>
    OpeningDebitBalance,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum Item1ChoiceType
{

    /// <remarks/>
    ClosingCreditBalance,

    /// <remarks/>
    ClosingDebitBalance,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesTaxonomy
{

    /// <remarks/>
    public string TaxonomyReference;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxonomyElement")]
    public AuditFileMasterFilesTaxonomyTaxonomyElement[] TaxonomyElement;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesTaxonomyTaxonomyElement
{

    /// <remarks/>
    public string TaxonomyCode;

    /// <remarks/>
    public string TaxonomyClusterID;

    /// <remarks/>
    public string TaxonomyClusterContextID;

    /// <remarks/>
    public string AccountID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesCustomer : CompanyStructure
{

    /// <remarks/>
    public string CustomerID;

    /// <remarks/>
    public string SelfBillingIndicator;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OpeningCreditBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("OpeningDebitBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClosingCreditBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("ClosingDebitBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
    public decimal Item1;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public Item1ChoiceType1 Item1ElementName;

    /// <remarks/>
    public PartyInfoStructure PartyInfo;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemChoiceType1
{

    /// <remarks/>
    OpeningCreditBalance,

    /// <remarks/>
    OpeningDebitBalance,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum Item1ChoiceType1
{

    /// <remarks/>
    ClosingCreditBalance,

    /// <remarks/>
    ClosingDebitBalance,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesSupplier : CompanyStructure
{

    /// <remarks/>
    public string SupplierID;

    /// <remarks/>
    public string SelfBillingIndicator;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OpeningCreditBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("OpeningDebitBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClosingCreditBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("ClosingDebitBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
    public decimal Item1;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public Item1ChoiceType2 Item1ElementName;

    /// <remarks/>
    public PartyInfoStructure PartyInfo;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemChoiceType2
{

    /// <remarks/>
    OpeningCreditBalance,

    /// <remarks/>
    OpeningDebitBalance,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum Item1ChoiceType2
{

    /// <remarks/>
    ClosingCreditBalance,

    /// <remarks/>
    ClosingDebitBalance,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesTaxTableEntry
{

    /// <remarks/>
    public AuditFileMasterFilesTaxTableEntryTaxType TaxType;

    /// <remarks/>
    public AuditFileMasterFilesTaxTableEntryDescription Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxCodeDetails")]
    public AuditFileMasterFilesTaxTableEntryTaxCodeDetails[] TaxCodeDetails;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum AuditFileMasterFilesTaxTableEntryTaxType
{

    /// <remarks/>
    MVA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum AuditFileMasterFilesTaxTableEntryDescription
{

    /// <remarks/>
    Merverdiavgift,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesTaxTableEntryTaxCodeDetails
{

    /// <remarks/>
    public string TaxCode;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime EffectiveDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EffectiveDateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime ExpirationDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExpirationDateSpecified;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FlatTaxRate", typeof(AmountStructure))]
    [System.Xml.Serialization.XmlElementAttribute("TaxPercentage", typeof(decimal))]
    public object Item;

    /// <remarks/>
    public string Country;

    /// <remarks/>
    public string Region;

    /// <remarks/>
    public string StandardTaxCode;

    /// <remarks/>
    public bool Compensation;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompensationSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BaseRate")]
    public decimal[] BaseRate;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesUOMTableEntry
{

    /// <remarks/>
    public string UnitOfMeasure;

    /// <remarks/>
    public string Description;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesAnalysisTypeTableEntry
{

    /// <remarks/>
    public string AnalysisType;

    /// <remarks/>
    public string AnalysisTypeDescription;

    /// <remarks/>
    public string AnalysisID;

    /// <remarks/>
    public string AnalysisIDDescription;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime StartDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartDateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime EndDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified;

    /// <remarks/>
    public AuditFileMasterFilesAnalysisTypeTableEntryStatus Status;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Analysis")]
    public AnalysisPartyInfoStructure[] Analysis;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum AuditFileMasterFilesAnalysisTypeTableEntryStatus
{

    /// <remarks/>
    Active,

    /// <remarks/>
    Closed,

    /// <remarks/>
    Observation,

    /// <remarks/>
    Passive,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesMovementTypeTableEntry
{

    /// <remarks/>
    public string MovementType;

    /// <remarks/>
    public string Description;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesProduct
{

    /// <remarks/>
    public string ProductCode;

    /// <remarks/>
    public string GoodsServicesID;

    /// <remarks/>
    public string ProductGroup;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    public string ProductCommodityCode;

    /// <remarks/>
    public string ProductNumberCode;

    /// <remarks/>
    public string ValuationMethod;

    /// <remarks/>
    public string UOMBase;

    /// <remarks/>
    public string UOMStandard;

    /// <remarks/>
    public decimal UOMToUOMBaseConversionFactor;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tax")]
    public AuditFileMasterFilesProductTax[] Tax;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesProductTax
{

    /// <remarks/>
    public string TaxType;

    /// <remarks/>
    public string TaxCode;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesPhysicalStockEntry
{

    /// <remarks/>
    public string WarehouseID;

    /// <remarks/>
    public string LocationID;

    /// <remarks/>
    public string ProductCode;

    /// <remarks/>
    public string StockAccountNo;

    /// <remarks/>
    public string ProductType;

    /// <remarks/>
    public string ProductStatus;

    /// <remarks/>
    public string StockAccountCommodityCode;

    /// <remarks/>
    public string OwnerID;

    /// <remarks/>
    public string UOMPhysicalStock;

    /// <remarks/>
    public decimal UOMToUOMBaseConversionFactor;

    /// <remarks/>
    public decimal UnitPrice;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitPriceSpecified;

    /// <remarks/>
    public decimal OpeningStockQuantity;

    /// <remarks/>
    public decimal OpeningStockValue;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OpeningStockValueSpecified;

    /// <remarks/>
    public decimal ClosingStockQuantity;

    /// <remarks/>
    public decimal ClosingStockValue;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClosingStockValueSpecified;

    /// <remarks/>
    public AuditFileMasterFilesPhysicalStockEntryStockCharacteristics StockCharacteristics;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesPhysicalStockEntryStockCharacteristics
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StockCharacteristic")]
    public string[] StockCharacteristic;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StockCharacteristicValue")]
    public string[] StockCharacteristicValue;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesOwner : CompanyStructure
{

    /// <remarks/>
    public string OwnerID;

    /// <remarks/>
    public string AccountID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesAsset
{

    /// <remarks/>
    public string AssetID;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Supplier")]
    public AuditFileMasterFilesAssetSupplier[] Supplier;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime PurchaseOrderDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PurchaseOrderDateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime DateOfAcquisition;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime StartUpDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartUpDateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Valuation", IsNullable = false)]
    public AuditFileMasterFilesAssetValuation[] Valuations;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesAssetSupplier
{

    /// <remarks/>
    public string SupplierName;

    /// <remarks/>
    public string SupplierID;

    /// <remarks/>
    public AddressStructure PostalAddress;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesAssetValuation
{

    /// <remarks/>
    public string AssetValuationType;

    /// <remarks/>
    public string ValuationClass;

    /// <remarks/>
    public decimal AcquisitionAndProductionCostsBegin;

    /// <remarks/>
    public decimal AcquisitionAndProductionCostsEnd;

    /// <remarks/>
    public decimal InvestmentSupport;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvestmentSupportSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AssetLifeMonth", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("AssetLifeYear", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType3 ItemElementName;

    /// <remarks/>
    public decimal AssetAddition;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AssetAdditionSpecified;

    /// <remarks/>
    public decimal Transfers;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransfersSpecified;

    /// <remarks/>
    public decimal AssetDisposal;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AssetDisposalSpecified;

    /// <remarks/>
    public decimal BookValueBegin;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BookValueBeginSpecified;

    /// <remarks/>
    public string DepreciationMethod;

    /// <remarks/>
    public decimal DepreciationPercentage;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DepreciationPercentageSpecified;

    /// <remarks/>
    public decimal DepreciationForPeriod;

    /// <remarks/>
    public decimal AppreciationForPeriod;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AppreciationForPeriodSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtraordinaryDepreciationForPeriod", IsNullable = false)]
    public AuditFileMasterFilesAssetValuationExtraordinaryDepreciationForPeriod[] ExtraordinaryDepreciationsForPeriod;

    /// <remarks/>
    public decimal AccumulatedDepreciation;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccumulatedDepreciationSpecified;

    /// <remarks/>
    public decimal BookValueEnd;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemChoiceType3
{

    /// <remarks/>
    AssetLifeMonth,

    /// <remarks/>
    AssetLifeYear,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileMasterFilesAssetValuationExtraordinaryDepreciationForPeriod
{

    /// <remarks/>
    public string ExtraordinaryDepreciationMethod;

    /// <remarks/>
    public decimal ExtraordinaryDepreciationForPeriod;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileGeneralLedgerEntries
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string NumberOfEntries;

    /// <remarks/>
    public decimal TotalDebit;

    /// <remarks/>
    public decimal TotalCredit;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Journal")]
    public AuditFileGeneralLedgerEntriesJournal[] Journal;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileGeneralLedgerEntriesJournal
{

    /// <remarks/>
    public string JournalID;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    public string Type;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transaction")]
    public AuditFileGeneralLedgerEntriesJournalTransaction[] Transaction;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileGeneralLedgerEntriesJournalTransaction
{

    /// <remarks/>
    public string TransactionID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string Period;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string PeriodYear;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime TransactionDate;

    /// <remarks/>
    public string SourceID;

    /// <remarks/>
    public string TransactionType;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    public string BatchID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime SystemEntryDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime GLPostingDate;

    /// <remarks/>
    public string CustomerID;

    /// <remarks/>
    public string SupplierID;

    /// <remarks/>
    public string SystemID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public AuditFileGeneralLedgerEntriesJournalTransactionLine[] Line;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileGeneralLedgerEntriesJournalTransactionLine
{

    /// <remarks/>
    public string RecordID;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Analysis")]
    public AnalysisStructure[] Analysis;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime ValueDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValueDateSpecified;

    /// <remarks/>
    public string SourceDocumentID;

    /// <remarks/>
    public string CustomerID;

    /// <remarks/>
    public string SupplierID;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CreditAmount", typeof(AmountStructure))]
    [System.Xml.Serialization.XmlElementAttribute("DebitAmount", typeof(AmountStructure))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public AmountStructure Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType4 ItemElementName;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxInformation")]
    public TaxInformationStructure[] TaxInformation;

    /// <remarks/>
    public string ReferenceNumber;

    /// <remarks/>
    public string CID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime DueDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DueDateSpecified;

    /// <remarks/>
    public decimal Quantity;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QuantitySpecified;

    /// <remarks/>
    public string CrossReference;

    /// <remarks/>
    public System.DateTime SystemEntryTime;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SystemEntryTimeSpecified;

    /// <remarks/>
    public string OwnerID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:StandardAuditFile-Taxation-Financial:NO", IncludeInSchema = false)]
public enum ItemChoiceType4
{

    /// <remarks/>
    CreditAmount,

    /// <remarks/>
    DebitAmount,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocuments
{

    /// <remarks/>
    public AuditFileSourceDocumentsSalesInvoices SalesInvoices;

    /// <remarks/>
    public AuditFileSourceDocumentsPurchaseInvoices PurchaseInvoices;

    /// <remarks/>
    public AuditFileSourceDocumentsPayments Payments;

    /// <remarks/>
    public AuditFileSourceDocumentsMovementOfGoods MovementOfGoods;

    /// <remarks/>
    public AuditFileSourceDocumentsAssetTransactions AssetTransactions;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsSalesInvoices
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string NumberOfEntries;

    /// <remarks/>
    public decimal TotalDebit;

    /// <remarks/>
    public decimal TotalCredit;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Invoice")]
    public InvoiceStructure[] Invoice;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsPurchaseInvoices
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string NumberOfEntries;

    /// <remarks/>
    public decimal TotalDebit;

    /// <remarks/>
    public decimal TotalCredit;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Invoice")]
    public InvoiceStructure[] Invoice;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsPayments
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string NumberOfEntries;

    /// <remarks/>
    public decimal TotalDebit;

    /// <remarks/>
    public decimal TotalCredit;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Payment")]
    public AuditFileSourceDocumentsPaymentsPayment[] Payment;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsPaymentsPayment
{

    /// <remarks/>
    public string PaymentRefNo;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string Period;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string PeriodYear;

    /// <remarks/>
    public string TransactionID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime TransactionDate;

    /// <remarks/>
    public string PaymentMethod;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    public string BatchID;

    /// <remarks/>
    public string SystemID;

    /// <remarks/>
    public string SourceID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public AuditFileSourceDocumentsPaymentsPaymentLine[] Line;

    /// <remarks/>
    public AuditFileSourceDocumentsPaymentsPaymentSettlement Settlement;

    /// <remarks/>
    public AuditFileSourceDocumentsPaymentsPaymentDocumentTotals DocumentTotals;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsPaymentsPaymentLine
{

    /// <remarks/>
    public string LineNumber;

    /// <remarks/>
    public string SourceDocumentID;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Analysis")]
    public AnalysisStructure[] Analysis;

    /// <remarks/>
    public string CustomerID;

    /// <remarks/>
    public string SupplierID;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime TaxPointDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxPointDateSpecified;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    public AuditFileSourceDocumentsPaymentsPaymentLineDebitCreditIndicator DebitCreditIndicator;

    /// <remarks/>
    public AmountStructure PaymentLineAmount;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxInformation")]
    public TaxInformationStructure[] TaxInformation;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public enum AuditFileSourceDocumentsPaymentsPaymentLineDebitCreditIndicator
{

    /// <remarks/>
    D,

    /// <remarks/>
    C,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsPaymentsPaymentSettlement
{

    /// <remarks/>
    public string SettlementDiscount;

    /// <remarks/>
    public AmountStructure SettlementAmount;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime SettlementDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SettlementDateSpecified;

    /// <remarks/>
    public string PaymentMechanism;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsPaymentsPaymentDocumentTotals
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxInformationTotals")]
    public TaxInformationStructure[] TaxInformationTotals;

    /// <remarks/>
    public decimal NetTotal;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NetTotalSpecified;

    /// <remarks/>
    public decimal GrossTotal;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsMovementOfGoods
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string NumberOfMovementLines;

    /// <remarks/>
    public decimal TotalQuantityReceived;

    /// <remarks/>
    public decimal TotalQuantityIssued;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StockMovement")]
    public AuditFileSourceDocumentsMovementOfGoodsStockMovement[] StockMovement;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsMovementOfGoodsStockMovement
{

    /// <remarks/>
    public string MovementReference;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime MovementDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime MovementPostingDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MovementPostingDateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
    public System.DateTime MovementPostingTime;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MovementPostingTimeSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime TaxPointDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxPointDateSpecified;

    /// <remarks/>
    public string MovementType;

    /// <remarks/>
    public string SourceID;

    /// <remarks/>
    public string SystemID;

    /// <remarks/>
    public AuditFileSourceDocumentsMovementOfGoodsStockMovementDocumentReference DocumentReference;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public AuditFileSourceDocumentsMovementOfGoodsStockMovementLine[] Line;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsMovementOfGoodsStockMovementDocumentReference
{

    /// <remarks/>
    public string DocumentType;

    /// <remarks/>
    public string DocumentNumber;

    /// <remarks/>
    public string DocumentLine;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsMovementOfGoodsStockMovementLine
{

    /// <remarks/>
    public string LineNumber;

    /// <remarks/>
    public string AccountID;

    /// <remarks/>
    public string TransactionID;

    /// <remarks/>
    public string CustomerID;

    /// <remarks/>
    public string SupplierID;

    /// <remarks/>
    public ShippingPointStructure ShipTo;

    /// <remarks/>
    public ShippingPointStructure ShipFrom;

    /// <remarks/>
    public string ProductCode;

    /// <remarks/>
    public string StockAccountNo;

    /// <remarks/>
    public decimal Quantity;

    /// <remarks/>
    public string UnitOfMeasure;

    /// <remarks/>
    public decimal UOMToUOMPhysicalStockConversionFactor;

    /// <remarks/>
    public decimal BookValue;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BookValueSpecified;

    /// <remarks/>
    public string MovementSubType;

    /// <remarks/>
    public string MovementComments;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxInformation")]
    public TaxInformationStructure[] TaxInformation;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsAssetTransactions
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string NumberOfAssetTransactions;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AssetTransaction")]
    public AuditFileSourceDocumentsAssetTransactionsAssetTransaction[] AssetTransaction;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsAssetTransactionsAssetTransaction
{

    /// <remarks/>
    public string AssetTransactionID;

    /// <remarks/>
    public string AssetID;

    /// <remarks/>
    public string AssetTransactionType;

    /// <remarks/>
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime AssetTransactionDate;

    /// <remarks/>
    public AuditFileSourceDocumentsAssetTransactionsAssetTransactionSupplier Supplier;

    /// <remarks/>
    public string TransactionID;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AssetTransactionValuation", IsNullable = false)]
    public AuditFileSourceDocumentsAssetTransactionsAssetTransactionAssetTransactionValuation[] AssetTransactionValuations;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsAssetTransactionsAssetTransactionSupplier
{

    /// <remarks/>
    public string SupplierName;

    /// <remarks/>
    public string SupplierID;

    /// <remarks/>
    public AddressStructure PostalAddress;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:StandardAuditFile-Taxation-Financial:NO")]
public partial class AuditFileSourceDocumentsAssetTransactionsAssetTransactionAssetTransactionValuation
{

    /// <remarks/>
    public string AssetValuationType;

    /// <remarks/>
    public decimal AcquisitionAndProductionCostsOnTransaction;

    /// <remarks/>
    public decimal BookValueOnTransaction;

    /// <remarks/>
    public decimal AssetTransactionAmount;
}
