using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GneissBooks;

internal class SaftStandardAccounts
{
    /// <summary>
    /// Container for Standard Account data
    /// </summary>
    public class StandardAccount
    {
        public string AccountIDStr { get { return AccountID.ToString(CultureInfo.InvariantCulture); } }
        public ushort AccountID { get; private set; }
        public string Description { get; private set; }

        public StandardAccount(ushort accountId, string description)
        {
            AccountID = accountId;
            Description = description;
        }
    }

    /// <summary>
    /// Array of all Standard Accounts
    /// </summary>
    private static StandardAccount[] standardAccounts = {
                new StandardAccount(10, "Immaterielle eiendeler o.l."),
                new StandardAccount(11, "Tomter, bygninger og annen fast eiendom"),
                new StandardAccount(12, "Transportmidler, inventar, maskiner o.l. "),
                new StandardAccount(13, "Finansielle anleggsmidler"),
                new StandardAccount(14, "Varelager og forskudd til leverandører"),
                new StandardAccount(15, "Kortsiktige fordringer"),
                new StandardAccount(16, "Merverdiavgift, opptjente offentlige tilskudd o.l. "),
                new StandardAccount(17, "Forskuddsbetalt kostnad, påløpt inntekt o.l. "),
                new StandardAccount(18, "Kortsiktige finansinvesteringer"),
                new StandardAccount(19, "Kontanter, bankinnskudd o.l."),
                new StandardAccount(20, "Egenkapital AS/ASA / Egenkapital andre foretak (inkl. samvirkeforetak)"),
                new StandardAccount(21, "Avsetning for forpliktelser"),
                new StandardAccount(22, "Annen langsiktig gjeld"),
                new StandardAccount(23, "Kortsiktige konvertible lån, obligasjonslån og gjeld til kredittinstitusjoner"),
                new StandardAccount(24, "Leverandørgjeld"),
                new StandardAccount(25, "Betalbar skatt"),
                new StandardAccount(26, "Skattetrekk og andre trekk"),
                new StandardAccount(27, "Skyldige offentlige avgifter"),
                new StandardAccount(28, "Utbytte"),
                new StandardAccount(29, "Annen kortsiktig gjeld"),
                new StandardAccount(30, "Salgsinntekt, avgiftspliktig"),
                new StandardAccount(31, "Salgsinntekt, avgiftsfri"),
                new StandardAccount(32, "Salgsinntekt, unntatt avgiftsplikt"),
                new StandardAccount(33, "Offentlig avgift vedrørende omsetning"),
                new StandardAccount(34, "Offentlig tilskudd/refusjon"),
                new StandardAccount(35, "Uopptjent inntekt"),
                new StandardAccount(36, "Leieinntekt"),
                new StandardAccount(37, "Provisjonsinntekt"),
                new StandardAccount(38, "Gevinst ved avgang av anleggsmidler (konto 380-384 samt 388-389). Verdiendring (konto 385-389)."),
                new StandardAccount(39, "Annen driftsrelatert inntekt"),
                new StandardAccount(40, "Forbruk av råvarer og innkjøpte halvfabrikata"),
                new StandardAccount(41, "Forbruk av varer under tilvirkning"),
                new StandardAccount(42, "Forbruk av ferdig tilvirkede varer"),
                new StandardAccount(43, "Forbruk av innkjøpte varer for videresalg"),
                new StandardAccount(45, "Fremmedytelse og underentreprise"),
                new StandardAccount(46, "Annen varekostnad"),
                new StandardAccount(49, "Annen periodisering"),
                new StandardAccount(50, "Lønn til ansatte"),
                new StandardAccount(52, "Fordel i arbeidsforhold"),
                new StandardAccount(53, "Annen opplysningspliktig godtgjørelse"),
                new StandardAccount(54, "Arbeidsgiveravgift og pensjonskostnad"),
                new StandardAccount(55, "Annen kostnadsgodtgjørelse"),
                new StandardAccount(56, "Arbeidsgodtgjørelse til eiere o.l. "),
                new StandardAccount(57, "Offentlig tilskudd vedrørende arbeidskraft"),
                new StandardAccount(58, "Offentlig refusjon vedrørende arbeidskraft"),
                new StandardAccount(59, "Annen personalkostnad"),
                new StandardAccount(60, "Av- og nedskrivning"),
                new StandardAccount(61, "Frakt og transportkostnad vedrørende salg"),
                new StandardAccount(62, "Energi, brensel og vann vedrørende produksjon"),
                new StandardAccount(63, "Kostnad lokaler"),
                new StandardAccount(64, "Leie maskiner, inventar, o.l. "),
                new StandardAccount(65, "Verktøy, inventar og driftsmateriale som ikke skal aktiveres"),
                new StandardAccount(66, "Reparasjon og vedlikehold "),
                new StandardAccount(67, "Fremmed tjeneste"),
                new StandardAccount(68, "Kontorkostnad, trykksak o.l. "),
                new StandardAccount(69, "Telefon og porto o.l. "),
                new StandardAccount(70, "Kostnad transportmidler"),
                new StandardAccount(71, "Kostnad og godtgjørelse for reise, diett, bil, o.l. "),
                new StandardAccount(72, "Provisjonskostnad"),
                new StandardAccount(73, "Salgs-, reklame- og representasjonskostnader"),
                new StandardAccount(74, "Kontingent og gave"),
                new StandardAccount(75, "Forsikringspremie, garanti- og servicekostnad"),
                new StandardAccount(76, "Lisens- og patentkostnad"),
                new StandardAccount(77, "Annen kostnad"),
                new StandardAccount(78, "Tap o.l. "),
                new StandardAccount(79, "Periodiseringskonto"),
                new StandardAccount(80, "Finansinntekt"),
                new StandardAccount(81, "Finanskostnad"),
                new StandardAccount(83, "Skattekostnad på ordinært resultat"),
                new StandardAccount(84, "Ekstraordinær inntekt"),
                new StandardAccount(85, "Ekstraordinær kostnad "),
                new StandardAccount(86, "Skattekostnad på ekstraordinært resultat"),
                new StandardAccount(88, "Årsresultat"),
                new StandardAccount(89, "Overføringer og disponeringer"),
                new StandardAccount(1000, "Forskning og utvikling, ervervet"),
                new StandardAccount(1005, "Forskning og utvikling, egenutviklet"),
                new StandardAccount(1020, "Konsesjoner, ervervet"),
                new StandardAccount(1025, "Konsesjoner, egenutviklet"),
                new StandardAccount(1030, "Patenter, ervervet "),
                new StandardAccount(1035, "Patenter, egenutviklet"),
                new StandardAccount(1040, "Lisenser, ervervet"),
                new StandardAccount(1045, "Lisenser, egenutviklet"),
                new StandardAccount(1050, "Varemerker, ervervet"),
                new StandardAccount(1055, "Varemerker, egenutviklet"),
                new StandardAccount(1060, "Andre rettigheter, ervervet"),
                new StandardAccount(1065, "Andre rettigheter, egenutviklet"),
                new StandardAccount(1068, "Innenlands kjøp av rettigheter, omvendt avgiftsplikt"),
                new StandardAccount(1069, "Innenlands kjøp av rettigheter, omvendt avgiftsplikt, motkonto"),
                new StandardAccount(1070, "Utsatt skattefordel, brutto"),
                new StandardAccount(1075, "Reduksjon utsatt skattefordel pga manglende realiserbarhet"),
                new StandardAccount(1079, "Utlignbar utsatt skattefordel"),
                new StandardAccount(1080, "Goodwill"),
                new StandardAccount(1100, "Bygninger"),
                new StandardAccount(1110, "Fast teknisk installasjon i bygning"),
                new StandardAccount(1120, "Bygningsmessige anlegg"),
                new StandardAccount(1130, "Anlegg under utførelse"),
                new StandardAccount(1140, "Jordbrukseiendommer"),
                new StandardAccount(1145, "Skogbrukseiendommer"),
                new StandardAccount(1150, "Tomter"),
                new StandardAccount(1155, "Andre grunnarealer"),
                new StandardAccount(1160, "Boliger inklusive tomter"),
                new StandardAccount(1180, "Investeringseiendommer"),
                new StandardAccount(1190, "Grunnlag MVA innførsel av varer, høy sats"),
                new StandardAccount(1191, "Grunnlag MVA innførsel av varer, høy sats, motkonto"),
                new StandardAccount(1192, "Grunnlag MVA innførsel av varer, middels sats"),
                new StandardAccount(1193, "Grunnlag MVA innførsel av varer, middels sats, motkonto"),
                new StandardAccount(1194, "Grunnlag innførsel av varer med null sats"),
                new StandardAccount(1195, "Grunnlag innførsel av varer med  null sats, motkonto"),
                new StandardAccount(1196, "Grunnlag utgående MVA kjøp tjenester fra utlandet "),
                new StandardAccount(1197, "Grunnlag utgående MVA kjøp tjenester fra utlandet, motkonto"),
                new StandardAccount(1200, "Maskiner og anlegg"),
                new StandardAccount(1210, "Maskiner og anlegg under utførelse"),
                new StandardAccount(1220, "Skip"),
                new StandardAccount(1224, "Rigger"),
                new StandardAccount(1225, "Fly"),
                new StandardAccount(1230, "Personbiler/stasjonsvogner"),
                new StandardAccount(1235, "Varebiler, klasse 1"),
                new StandardAccount(1236, "Varebiler, klasse 2"),
                new StandardAccount(1237, "Lastebiler"),
                new StandardAccount(1238, "Busser"),
                new StandardAccount(1239, "Varebiler med nullutslipp"),
                new StandardAccount(1240, "Traktorer"),
                new StandardAccount(1242, "Trucker"),
                new StandardAccount(1249, "Andre transportmidler"),
                new StandardAccount(1250, "Inventar"),
                new StandardAccount(1260, "Fast bygningsinventar, eget bygg"),
                new StandardAccount(1265, "Fast bygningsinventar, leide lokaler"),
                new StandardAccount(1290, "Grunnlag MVA innførsel av varer, høy sats"),
                new StandardAccount(1291, "Grunnlag MVA innførsel av varer, høy sats, motkonto"),
                new StandardAccount(1292, "Grunnlag MVA innførsel av varer, middels sats"),
                new StandardAccount(1293, "Grunnlag MVA innførsel av varer, middels sats, motkonto"),
                new StandardAccount(1294, "Grunnlag innførsel av varer med null sats"),
                new StandardAccount(1295, "Grunnlag innførsel av varer med null sats, motkonto"),
                new StandardAccount(1296, "Grunnlag utgående MVA kjøp tjenester fra utlandet"),
                new StandardAccount(1297, "Grunnlag utgående MVA kjøp tjenester fra utlandet, motkonto"),
                new StandardAccount(1300, "Aksjer i datterselskap"),
                new StandardAccount(1305, "Andeler i datterselskap"),
                new StandardAccount(1306, "Aksjer/andeler i datterselskap, utenlandske, innenfor fritaksmetoden"),
                new StandardAccount(1308, "Aksjer/andeler i datterselskap, utenlandske, utenfor fritaksmetoden"),
                new StandardAccount(1310, "Aksjer i foretak i samme konsern"),
                new StandardAccount(1315, "Andeler i foretak i samme konsern"),
                new StandardAccount(1316, "Aksjer/andeler i foretak i samme konsern, utenlandske, innenfor fritaksmetoden"),
                new StandardAccount(1318, "Aksjer/andeler i foretak i samme konsern, utenlandske, utenfor fritaksmetoden"),
                new StandardAccount(1320, "Lån til datterselskaper"),
                new StandardAccount(1325, "Lån til andre foretak i samme konsern"),
                new StandardAccount(1330, "Investeringer i tilknyttet selskap"),
                new StandardAccount(1340, "Lån til tilknyttet selskap"),
                new StandardAccount(1345, "Lån til felles kontrollert virksomhet"),
                new StandardAccount(1350, "Andre aksjer, norske"),
                new StandardAccount(1355, "Andre andeler, norske"),
                new StandardAccount(1356, "Andre aksjer/andeler, utenlandske, innenfor fritaksmetoden"),
                new StandardAccount(1357, "Andre aksjer/andeler, utenlandske, utenfor fritaksmetoden"),
                new StandardAccount(1358, "Verdipapirfondsandeler"),
                new StandardAccount(1360, "Obligasjoner"),
                new StandardAccount(1370, "Fordringer på eiere"),
                new StandardAccount(1375, "Fordringer på styremedlemmer"),
                new StandardAccount(1380, "Fordringer på ansatte"),
                new StandardAccount(1384, "Fordringer på daglig leder"),
                new StandardAccount(1385, "Fordringer på ansatte eiere"),
                new StandardAccount(1393, "Innskuddsfond"),
                new StandardAccount(1394, "Overfinansiering av pensjonsforpliktelser (pensjonspremiefond)"),
                new StandardAccount(1395, "Leietakerinnskudd"),
                new StandardAccount(1396, "Depositum"),
                new StandardAccount(1397, "Forskuddsleasing"),
                new StandardAccount(1398, "Til gode merverdiavgift"),
                new StandardAccount(1399, "Andre fordringer"),
                new StandardAccount(1400, "Direkte materialer/råvarer"),
                new StandardAccount(1405, "Hjelpematerialer"),
                new StandardAccount(1408, "Driftsmaterialer og reservedeler"),
                new StandardAccount(1409, "Beholdningsendring råvarer og innkjøpte halvfabrikater"),
                new StandardAccount(1420, "Varer under tilvirkning"),
                new StandardAccount(1429, "Beholdningsendring varer under tilvirkning"),
                new StandardAccount(1440, "Ferdige egentilvirkede varer"),
                new StandardAccount(1449, "Beholdningsendring ferdige egentilvirkede varer"),
                new StandardAccount(1460, "Innkjøpte varer for videresalg"),
                new StandardAccount(1465, "Demonstrasjonsvarer"),
                new StandardAccount(1469, "Beholdningsendring innkjøpte varer for videresalg"),
                new StandardAccount(1470, "Grunnlag MVA innførsel av varer, høy sats"),
                new StandardAccount(1471, "Grunnlag MVA innførsel av varer, høy sats, motkonto"),
                new StandardAccount(1472, "Grunnlag MVA innførsel av varer, middels sats"),
                new StandardAccount(1473, "Grunnlag MVA innførsel av varer, middels sats, motkonto"),
                new StandardAccount(1474, "Grunnlag innførsel av varer med null sats"),
                new StandardAccount(1475, "Grunnlag innførsel av varer med  null sats, motkonto"),
                new StandardAccount(1476, "Grunnlag utgående MVA kjøp tjenester fra utlandet "),
                new StandardAccount(1477, "Grunnlag utgående MVA kjøp tjenester fra utlandet, motkonto"),
                new StandardAccount(1478, "Innenlands kjøp av varer og tjenester, omvendt avgiftsplikt"),
                new StandardAccount(1479, "Innenlands kjøp av varer og tjenester, omvendt avgiftsplikt, motkonto"),
                new StandardAccount(1480, "Forskuddsbetaling til leverandører (varekontrakter/prosjekter)"),
                new StandardAccount(1490, "Biologiske eiendeler"),
                new StandardAccount(1500, "Kundefordringer"),
                new StandardAccount(1530, "Opptjent, ikke fakturert driftsinntekt"),
                new StandardAccount(1550, "Kundefordringer på selskap i samme konsern"),
                new StandardAccount(1560, "Andre fordringer på selskap i samme konsern"),
                new StandardAccount(1570, "Reiseforskudd"),
                new StandardAccount(1572, "Lønnsforskudd (som trekkes i lønn senere)"),
                new StandardAccount(1573, "Andre kortsiktige lån til ansatte (ikke forskudd lønn)"),
                new StandardAccount(1574, "Kortsiktig lån aksjonær/deltaker"),
                new StandardAccount(1575, "Mellomregning aksjonær/deltaker"),
                new StandardAccount(1576, "Kortsiktig lån daglig leder"),
                new StandardAccount(1579, "Andre kortsiktige fordringer"),
                new StandardAccount(1580, "Avsetning tap på kundefordringer"),
                new StandardAccount(1585, "Avsetning tap på andre fordringer"),
                new StandardAccount(1590, "Andre omløpsmidler"),
                new StandardAccount(1600, "Utgående merverdiavgift, høy sats"),
                new StandardAccount(1601, "Utgående merverdiavgift, middels sats"),
                new StandardAccount(1602, "Utgående merverdiavgift, middels sats"),
                new StandardAccount(1603, "Utgående merverdiavgift, lav sats"),
                new StandardAccount(1604, "Utgående merverdiavgift kjøp tjenester fra utlandet"),
                new StandardAccount(1605, "Utgående merverdiavgift - innførsel av varer, høy sats"),
                new StandardAccount(1606, "Utgående merverdiavgift - innførsel av varer, middels sats"),
                new StandardAccount(1607, "Utgående merverdiavgift - innenlands kjøp av varer og tjenester med omvendt avgiftsplikt, høy sats"),
                new StandardAccount(1610, "Inngående merverdiavgift, høy sats"),
                new StandardAccount(1611, "Inngående merverdiavgift, middels sats"),
                new StandardAccount(1612, "Inngående merverdiavgift, middels sats, råfisk mv"),
                new StandardAccount(1613, "Inngående merverdiavgift, lav sats"),
                new StandardAccount(1614, "Inngående merverdiavgift kjøp tjenester fra utlandet"),
                new StandardAccount(1615, "Inngående merverdiavgift - innførsel av varer, høy sats"),
                new StandardAccount(1616, "Inngående merverdiavgift - innførsel av varer, middels sats"),
                new StandardAccount(1617, "Inngående merverdiavgift - innenlands kjøp av varer og tjenester med omvendt avgiftsplikt, høy sats"),
                new StandardAccount(1640, "Oppgjørskonto merverdiavgift"),
                new StandardAccount(1650, "Merverdiavgiftskompensasjon, høy sats"),
                new StandardAccount(1651, "Merverdiavgiftskompensasjon, middels sats"),
                new StandardAccount(1652, "Merverdiavgiftskompensasjon, lav sats"),
                new StandardAccount(1654, "Oppgjørskonto kompensert merverdiavgift"),
                new StandardAccount(1655, "Grunnlag merverdiavgiftskompensasjon, høy sats"),
                new StandardAccount(1656, "Grunnlag merverdiavgiftskompensasjon, middels sats"),
                new StandardAccount(1657, "Grunnlag merverdiavgiftskompensasjon, lav sats"),
                new StandardAccount(1659, "Motkonto grunnlag merverdiavgiftskompensasjon "),
                new StandardAccount(1670, "Krav på offentlige tilskudd"),
                new StandardAccount(1675, "Skattefunn til gode, ikke fastsatt"),
                new StandardAccount(1700, "Forskuddsbetalt leiekostnad"),
                new StandardAccount(1710, "Forskuddsbetalt rentekostnad"),
                new StandardAccount(1740, "Forskuddsbetalt, ikke påløpt lønn"),
                new StandardAccount(1742, "Forskuddsbetalt strøm, varme mv."),
                new StandardAccount(1743, "Forskuddsbetalt forsikring"),
                new StandardAccount(1744, "Forskuddsbetalt leasingleie"),
                new StandardAccount(1749, "Andre forskuddsbetalte driftskostnader"),
                new StandardAccount(1750, "Påløpt leieinntekt"),
                new StandardAccount(1760, "Påløpt renteinntekt"),
                new StandardAccount(1780, "Krav på innbetaling av selskapskapital"),
                new StandardAccount(1800, "Aksjer i foretak i samme konsern, norske"),
                new StandardAccount(1805, "Andeler i foretak i samme konsern, norske"),
                new StandardAccount(1806, "Aksjer/andeler i foretak i samme konsern, utenlandske, innenfor fritaksmetoden"),
                new StandardAccount(1808, "Aksjer/andeler i foretak i samme konsern, utenlandske, utenfor fritaksmetoden"),
                new StandardAccount(1810, "Børsnoterte aksjer, norske"),
                new StandardAccount(1815, "Børsnoterte aksjer, utenlandske, innenfor fritaksmetoden"),
                new StandardAccount(1816, "Børsnoterte aksjer, utenlandske, utenfor fritaksmetoden"),
                new StandardAccount(1820, "Andre ikke børsnoterte aksjer, norske"),
                new StandardAccount(1825, "Andre ikke børsnoterte aksjer, utenlandske, innenfor fritaksmetoden"),
                new StandardAccount(1830, "Markedsbaserte obligasjoner, norske"),
                new StandardAccount(1835, "Markedsbaserte obligasjoner, utenlandske"),
                new StandardAccount(1840, "Ikke markedsbaserte obligasjoner, norske"),
                new StandardAccount(1845, "Ikke markedsbaserte obligasjoner, utenlandske"),
                new StandardAccount(1850, "Markedsbaserte obligasjoner med kort løpetid (sertifikater), norske"),
                new StandardAccount(1855, "Markedsbaserte obligasjoner med kort løpetid (sertifikater), utenlandske"),
                new StandardAccount(1860, "Ikke markedsbaserte obligasjoner med kort løpetid (sertifikater), norske"),
                new StandardAccount(1865, "Ikke markedsbaserte obligasjoner med kort løpetid (sertifikater), utenlandske"),
                new StandardAccount(1870, "Markedsbaserte opsjoner, norske"),
                new StandardAccount(1875, "Markedsbaserte opsjoner, utenlandske"),
                new StandardAccount(1880, "Ikke markedsbaserte opsjoner, norske"),
                new StandardAccount(1882, "Ikke markedsbaserte opsjoner, utenlandske"),
                new StandardAccount(1889, "Andre finansielle instrumenter"),
                new StandardAccount(1890, "Andeler utenfor konsern, norske"),
                new StandardAccount(1892, "Andeler utenfor konsern, utenlandske, innenfor fritaksmetoden"),
                new StandardAccount(1893, "Andeler utenfor konsern, utenlandske, utenfor fritaksmetoden"),
                new StandardAccount(1900, "Kontanter, NOK"),
                new StandardAccount(1905, "Kontanter, euro"),
                new StandardAccount(1908, "Kontanter, annen valuta"),
                new StandardAccount(1909, "Kassedifferanse"),
                new StandardAccount(1920, "Bankinnskudd"),
                new StandardAccount(1950, "Bankinnskudd for skattetrekk"),
                new StandardAccount(1960, "Bankinnskudd utland"),
                new StandardAccount(2000, "Aksjekapital / Egenkapital, bundet"),
                new StandardAccount(2010, "Egne aksjer / Felleseid andelskapital"),
                new StandardAccount(2020, "Overkurs"),
                new StandardAccount(2030, "Ikke registrert kapitalforhøyelse"),
                new StandardAccount(2032, "Ikke registrert fondsemisjon"),
                new StandardAccount(2033, "Ikke registrert kapitalnedsettelse"),
                new StandardAccount(2035, "Annen innskutt egenkapital"),
                new StandardAccount(2036, "Stiftelsesutgifter"),
                new StandardAccount(2040, "Fond / Fond for vurderingsforskjeller i DLS"),
                new StandardAccount(2042, "Fond for vurderingsforskjeller i andre selskaper"),
                new StandardAccount(2045, "Fond for urealiserte gevinster"),
                new StandardAccount(2050, "Annen egenkapital"),
                new StandardAccount(2055, "Avsatt utbytte"),
                new StandardAccount(2060, "Uttak kontanter"),
                new StandardAccount(2062, "Innskudd kontanter"),
                new StandardAccount(2063, "Uttak av anleggsmidler/driftsmidler"),
                new StandardAccount(2064, "Uttak varer og tjenester"),
                new StandardAccount(2065, "Egen bolig i næringsbygg"),
                new StandardAccount(2066, "Motkonto egen bolig i næringsbygg"),
                new StandardAccount(2067, "Lys og varme privat"),
                new StandardAccount(2068, "Private kostnader til elektronisk kommunikasjon"),
                new StandardAccount(2069, "Diverse andre privatutgifter"),
                new StandardAccount(2070, "Forskuddsskatt"),
                new StandardAccount(2072, "Tilleggsforskudd/restskatt"),
                new StandardAccount(2075, "Privat bruk av næringsbil"),
                new StandardAccount(2077, "Premie til egen syke- og ulykkesforsikring"),
                new StandardAccount(2078, "Premie til tilleggstrygd for sykepenger"),
                new StandardAccount(2080, "Udekket tap"),
                new StandardAccount(2099, "Udisponert resultat"),
                new StandardAccount(2100, "Pensjonsforpliktelser"),
                new StandardAccount(2120, "Utsatt skatt, brutto"),
                new StandardAccount(2129, "Utlignbar utsatt skatt"),
                new StandardAccount(2160, "Uopptjent inntekt"),
                new StandardAccount(2180, "Andre avsetninger for forpliktelser"),
                new StandardAccount(2188, "Avsetning for skyldig merverdiavgift"),
                new StandardAccount(2200, "Konvertible lån"),
                new StandardAccount(2210, "Obligasjonslån"),
                new StandardAccount(2220, "Gjeld til kredittinstitusjoner"),
                new StandardAccount(2250, "Gjeld til ansatte"),
                new StandardAccount(2255, "Gjeld til eiere"),
                new StandardAccount(2260, "Gjeld til selskap i samme konsern"),
                new StandardAccount(2280, "Stille interessentinnskudd"),
                new StandardAccount(2285, "Ansvarlig lånekapital"),
                new StandardAccount(2290, "Gjeld til andre personer enn ansatte og eiere"),
                new StandardAccount(2299, "Annen langsiktig gjeld"),
                new StandardAccount(2300, "Konvertible lån"),
                new StandardAccount(2320, "Obligasjonslån"),
                new StandardAccount(2360, "Byggelån "),
                new StandardAccount(2380, "Kassakreditt"),
                new StandardAccount(2390, "Annen gjeld til kredittinstitusjon"),
                new StandardAccount(2400, "Leverandørgjeld "),
                new StandardAccount(2460, "Leverandørgjeld til selskap i samme konsern"),
                new StandardAccount(2500, "Betalbar skatt, ikke fastsatt"),
                new StandardAccount(2510, "Betalbar skatt, fastsatt"),
                new StandardAccount(2540, "Forskuddsskatt – upersonlig skattyter"),
                new StandardAccount(2600, "Forskuddstrekk"),
                new StandardAccount(2610, "Utleggstrekk"),
                new StandardAccount(2620, "Bidragstrekk"),
                new StandardAccount(2630, "Trygdetrekk"),
                new StandardAccount(2640, "Forsikringstrekk"),
                new StandardAccount(2650, "Trukket fagforeningskontingent"),
                new StandardAccount(2690, "Andre trekk"),
                new StandardAccount(2700, "Utgående merverdiavgift, høy sats"),
                new StandardAccount(2701, "Utgående merverdiavgift, middels sats"),
                new StandardAccount(2702, "Utgående merverdiavgift, middels sats, råfisk mv"),
                new StandardAccount(2703, "Utgående merverdiavgift, lav sats"),
                new StandardAccount(2704, "Utgående merverdiavgift ved kjøp av tjenester fra utlandet"),
                new StandardAccount(2705, "Utgående merverdiavgift - innførsel av varer, høy sats"),
                new StandardAccount(2706, "Utgående merverdiavgift - innførsel av varer, middels sats"),
                new StandardAccount(2707, "Utgående merverdiavgift - innenlands kjøp av varer og tjenester med omvendt avgiftsplikt, høy sats"),
                new StandardAccount(2710, "Inngående merverdiavgift, høy sats"),
                new StandardAccount(2711, "Inngående merverdiavgift, middels sats"),
                new StandardAccount(2712, "Inngående merverdiavgift, middels sats, råfisk mv"),
                new StandardAccount(2713, "Inngående merverdiavgift, lav sats"),
                new StandardAccount(2714, "Inngående merverdiavgift ved kjøp tjenester fra utlandet"),
                new StandardAccount(2715, "Inngående merverdiavgift - innførsel av varer, høy sats"),
                new StandardAccount(2716, "Inngående merverdiavgift - innførsel av varer, middels sats"),
                new StandardAccount(2717, "Inngående merverdiavgift - innenlands kjøp av varer og tjenester med omvendt avgiftsplikt, høy sats"),
                new StandardAccount(2740, "Oppgjørskonto merverdiavgift"),
                new StandardAccount(2770, "Skyldig arbeidsgiveravgift"),
                new StandardAccount(2771, "Betalt arbeidsgiveravgift"),
                new StandardAccount(2772, "Skyldig finansskatt av lønn"),
                new StandardAccount(2773, "Betalt finansskatt av lønn"),
                new StandardAccount(2780, "Påløpt arbeidsgiveravgift påløpt lønn"),
                new StandardAccount(2781, "Påløpt arbeidsgiveravgift ferielønn"),
                new StandardAccount(2782, "Påløpt arbeidsgiveravgift andre honorarer"),
                new StandardAccount(2783, "Påløpt finansskatt påløpt lønn"),
                new StandardAccount(2784, "Påløpt finansskatt ferielønn"),
                new StandardAccount(2785, "Påløpt finansskatt andre honorarer"),
                new StandardAccount(2790, "Andre offentlige avgifter"),
                new StandardAccount(2800, "Avsatt utbytte"),
                new StandardAccount(2900, "Forskudd fra kunder"),
                new StandardAccount(2910, "Gjeld til ansatte"),
                new StandardAccount(2915, "Gjeld til eiere"),
                new StandardAccount(2920, "Gjeld til selskap i samme konsern"),
                new StandardAccount(2930, "Skyldig lønn"),
                new StandardAccount(2940, "Skyldige feriepenger"),
                new StandardAccount(2945, "Utbetalte feriepenger"),
                new StandardAccount(2950, "Påløpt rente"),
                new StandardAccount(2960, "Annen påløpt kostnad"),
                new StandardAccount(2965, "Forskuddsbetalt inntekt"),
                new StandardAccount(2970, "Fremtidig garantiytelse"),
                new StandardAccount(2975, "Fremtidig serviceytelse"),
                new StandardAccount(2980, "Avsetning styrehonorar"),
                new StandardAccount(2982, "Avsetning revisjonshonorar"),
                new StandardAccount(2983, "Avsetning regnskapshonorar"),
                new StandardAccount(2989, "Avsetning for andre forpliktelser"),
                new StandardAccount(2990, "Gjeld til andre personer enn ansatte og eiere"),
                new StandardAccount(2999, "Annen kortsiktig gjeld"),
                new StandardAccount(3000, "Salgsinntekt handelsvarer, avgiftspliktig, høy sats"),
                new StandardAccount(3005, "Salgsinntekt handelsvarer, omvendt avgiftsplikt"),
                new StandardAccount(3009, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3010, "Salgsinntekt egentilvirkede varer, avgiftspliktig, høy sats"),
                new StandardAccount(3015, "Salgsinntekt egentilvirkede varer, omvendt avgiftsplikt"),
                new StandardAccount(3019, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3020, "Salgsinntekt tjenester, avgiftspliktig, høy sats"),
                new StandardAccount(3025, "Salgsinntekt tjenester, omvendt avgiftsplikt"),
                new StandardAccount(3029, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3030, "Salgsinntekt handelsvarer, avgiftspliktig, middels sats"),
                new StandardAccount(3039, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3040, "Salgsinntekt egentilvirkede varer, avgiftspliktig, middels sats"),
                new StandardAccount(3049, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3050, "Salgsinntekt tjenester, avgiftspliktig, lav sats"),
                new StandardAccount(3059, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3060, "Uttak av varer, avgiftspliktig, høy sats"),
                new StandardAccount(3063, "Uttak av varer, avgiftspliktig, middels sats"),
                new StandardAccount(3070, "Uttak av tjenester, avgiftspliktig, høy sats"),
                new StandardAccount(3074, "Uttak av tjenester, avgiftspliktig, lav sats"),
                new StandardAccount(3081, "Kontantrabatt, avgiftspliktig salg, høy sats"),
                new StandardAccount(3082, "Kontantrabatt, avgiftspliktig salg, middel sats"),
                new StandardAccount(3083, "Kontantrabatt, avgiftspliktig salg, lav sats"),
                new StandardAccount(3084, "Kvantumsrabatt, avgiftspliktig salg, høy sats"),
                new StandardAccount(3085, "Kvantumsrabatt, avgiftspliktig salg, middels sats"),
                new StandardAccount(3086, "Kvantumsrabatt, avgiftspliktig salg, lav sats"),
                new StandardAccount(3087, "Annen salgsinntektsreduksjon, avgiftspliktig salg, høy sats"),
                new StandardAccount(3088, "Annen salgsinntektsreduksjon, avgiftspliktig salg, middels sats"),
                new StandardAccount(3089, "Annen salgsinntektsreduksjon, avgiftspliktig salg, lav sats"),
                new StandardAccount(3090, "Viderefakturering av omkostninger ved salg, høy sats"),
                new StandardAccount(3091, "Viderefakturering av omkostninger ved salg, middels sats"),
                new StandardAccount(3092, "Viderefakturering av omkostninger ved salg, lav sats"),
                new StandardAccount(3100, "Salgsinntekt handelsvarer, innenlands, avgiftsfri"),
                new StandardAccount(3105, "Salgsinntekt handelsvarer, utførsel, avgiftsfri"),
                new StandardAccount(3109, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3110, "Salgsinntekt egentilvirkede varer, innenlands, avgiftsfri"),
                new StandardAccount(3115, "Salgsinntekt egentilvirkede varer, utførsel, avgiftsfri"),
                new StandardAccount(3119, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3120, "Salgsinntekt tjenester, innenlands, avgiftsfri"),
                new StandardAccount(3125, "Salgsinntekt tjenester, utførsel, avgiftsfri"),
                new StandardAccount(3129, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3160, "Uttak av varer, avgiftsfritt"),
                new StandardAccount(3170, "Uttak av tjenester, avgiftsfritt"),
                new StandardAccount(3181, "Kontantrabatt, innenlands, avgiftsfritt"),
                new StandardAccount(3182, "Kontantrabatt, utførsel, avgiftsfritt"),
                new StandardAccount(3185, "Kvantumsrabatt, innenlands, avgiftsfritt"),
                new StandardAccount(3186, "Kvantumsrabatt, utførsel, avgiftsfritt"),
                new StandardAccount(3188, "Annen salgsinntektsreduksjon, innenlands, avgiftsfritt"),
                new StandardAccount(3189, "Annen salgsinntektsreduksjon, utførsel, avgiftsfritt"),
                new StandardAccount(3190, "Viderefakturering av omkostninger ved salg, innenlands, avgiftsfritt"),
                new StandardAccount(3191, "Viderefakturering av omkostninger ved salg, utførsel, avgiftsfritt"),
                new StandardAccount(3200, "Salgsinntekt handelsvarer, unntatt avgiftsplikt"),
                new StandardAccount(3209, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3210, "Salgsinntekt egentilvirkede varer, unntatt avgiftsplikt"),
                new StandardAccount(3219, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3220, "Salgsinntekt tjenester, unntatt avgiftsplikt"),
                new StandardAccount(3229, "Opptjent, ikke fakturert inntekt"),
                new StandardAccount(3260, "Uttak av varer, unntatt avgiftsplikt"),
                new StandardAccount(3281, "Kontantrabatt, unntatt avgiftsplikt"),
                new StandardAccount(3285, "Kvantumsrabatt, unntatt avgiftsplikt"),
                new StandardAccount(3289, "Annen salgsinntektsreduksjon, unntatt avgiftsplikt"),
                new StandardAccount(3290, "Viderefakturering av omkostninger ved salg, unntatt avgiftsplikt"),
                new StandardAccount(3300, "Spesiell offentlig avgift for tilvirkede/solgte varer"),
                new StandardAccount(3400, "Spesielt offentlig tilskudd for tilvirkede/solgte varer"),
                new StandardAccount(3440, "Spesielt offentlig tilskudd for tjeneste"),
                new StandardAccount(3500, "Garanti"),
                new StandardAccount(3510, "Service"),
                new StandardAccount(3600, "Leieinntekt fast eiendom, unntatt avgiftsplikt"),
                new StandardAccount(3605, "Leieinntekt fast eiendom, avgiftspliktig"),
                new StandardAccount(3609, "Opptjent, ikke fakturert leieinntekt"),
                new StandardAccount(3610, "Leieinntekt andre varige driftsmidler, avgiftspliktig"),
                new StandardAccount(3615, "Leieinntekt andre varige driftsmidler, avgiftsfri"),
                new StandardAccount(3619, "Opptjent, ikke fakturert leieinntekt"),
                new StandardAccount(3620, "Annen leieinntekt"),
                new StandardAccount(3700, "Provisjonsinntekt, avgiftspliktig"),
                new StandardAccount(3705, "Provisjonsinntekt, avgiftsfri"),
                new StandardAccount(3709, "Opptjent, ikke fakturert provisjonsinntekt"),
                new StandardAccount(3850, "Verdiendringer investeringseiendommer"),
                new StandardAccount(3870, "Verdiendringer biologiske eiendeler"),
                new StandardAccount(3881, "Salgssum immatr. eiendeler og varige driftsmidler, avgiftspliktig salg"),
                new StandardAccount(3882, "Salgssum immatr. eiendeler og varige driftsmidler, avgiftsfritt salg"),
                new StandardAccount(3889, "Motkonto balanseverdi solgte immatr. eiendeler og varige driftsmidler"),
                new StandardAccount(3891, "Salgssum finansielle anleggsmidler"),
                new StandardAccount(3899, "Motkonto balanseverdi finansielle anleggsmidler"),
                new StandardAccount(3900, "Annen driftsrelatert inntekt"),
                new StandardAccount(4000, "Innkjøp av råvarer og halvfabrikata, høy sats"),
                new StandardAccount(4030, "Innkjøp av råvarer og halvfabrikata, middels sats"),
                new StandardAccount(4040, "Utenlandsk innkjøp av råvarer og halvfabrikata, høy sats"),
                new StandardAccount(4041, "Utenlandsk innkjøp av råvarer og halvfabrikata, middels sats"),
                new StandardAccount(4042, "Utenlandsk innkjøp av råvarer og halvfabrikata, fritatt for avgift"),
                new StandardAccount(4060, "Frakt, toll og spedisjon"),
                new StandardAccount(4071, "Kontantrabatt, råvarer og halvfabrikata, høy sats"),
                new StandardAccount(4072, "Kontantrabatt, råvarer og halvfabrikata, middels sats"),
                new StandardAccount(4075, "Kvantumsrabatt, råvarer og halvfabrikata, høy sats"),
                new StandardAccount(4076, "Kvantumsrabatt, råvarer og halvfabrikata, middels sats"),
                new StandardAccount(4078, "Annen innkjøpsprisreduksjon, høy sats"),
                new StandardAccount(4079, "Annen innkjøpsprisreduksjon, middels sats"),
                new StandardAccount(4080, "Grunnlag MVA innførsel av varer, høy sats"),
                new StandardAccount(4081, "Grunnlag MVA innførsel av varer, høy sats, motkonto"),
                new StandardAccount(4082, "Grunnlag MVA innførsel av varer, middels sats"),
                new StandardAccount(4083, "Grunnlag MVA innførsel av varer, middels sats, motkonto"),
                new StandardAccount(4084, "Grunnlag innførsel av varer med null sats"),
                new StandardAccount(4085, "Grunnlag innførsel av varer med  null sats, motkonto"),
                new StandardAccount(4086, "Innenlands kjøp av varer, omvendt avgiftsplikt"),
                new StandardAccount(4087, "Innenlands kjøp av varer, omvendt avgiftsplikt, motkonto"),
                new StandardAccount(4090, "Beholdningsendring"),
                new StandardAccount(4100, "Innkjøp varer under tilvirkning, høy sats"),
                new StandardAccount(4130, "Innkjøp varer under tilvirkning, middels sats"),
                new StandardAccount(4160, "Frakt, toll og spedisjon"),
                new StandardAccount(4171, "Kontantrabatt, varer under tilvirkning, høy sats"),
                new StandardAccount(4172, "Kontantrabatt, varer under tilvirkning, middels sats"),
                new StandardAccount(4175, "Kvantumsrabatt, varer under tilvirkning, høy sats"),
                new StandardAccount(4176, "Kvantumsrabatt, varer under tilvirkning, middels sats"),
                new StandardAccount(4178, "Annen innkjøpsprisreduksjon, varer under tilvirkning, høy sats"),
                new StandardAccount(4179, "Annen innkjøpsprisreduksjon, varer under tilvirkning, middels sats"),
                new StandardAccount(4190, "Beholdningsendring"),
                new StandardAccount(4200, "Innkjøp ferdig egentilvirkede varer, høy ssats"),
                new StandardAccount(4230, "Innkjøp ferdig egentilvirkede varer, middels sats"),
                new StandardAccount(4260, "Frakt, toll og spedisjon"),
                new StandardAccount(4270, "Innkjøpsprisreduksjon, egentilvirkede varer, høy sats"),
                new StandardAccount(4271, "Innkjøpsprisreduksjon, egentilvirkede varer, middels sats"),
                new StandardAccount(4290, "Beholdningsendring"),
                new StandardAccount(4300, "Innkjøp av varer for videresalg, høy sats"),
                new StandardAccount(4330, "Innkjøp av varer for videresalg, middels sats"),
                new StandardAccount(4340, "Utenlands innkjøp av varer for videresalg, høy sats"),
                new StandardAccount(4341, "Utenlands innkjøp av varer for videresalg, middels sats"),
                new StandardAccount(4342, "Utenlands innkjøp av varer for videresalg, fritatt for avgift"),
                new StandardAccount(4360, "Frakt, toll og spedisjon"),
                new StandardAccount(4371, "Kontantrabatt, varer for videresalg, høy sats"),
                new StandardAccount(4372, "Kontantrabatt, varer for videresalg, middels sats"),
                new StandardAccount(4375, "Kvantumsrabatt, varer for videresalg, høy sats"),
                new StandardAccount(4376, "Kvantumsrabatt, varer for videresalg, middels sats"),
                new StandardAccount(4378, "Annen innkjøpsprisreduksjon, høy sats"),
                new StandardAccount(4379, "Annen innkjøpsprisreduksjon, middels sats"),
                new StandardAccount(4380, "Grunnlag MVA innførsel av varer, høy sats"),
                new StandardAccount(4381, "Grunnlag MVA innførsel av varer, høy sats, motkonto"),
                new StandardAccount(4382, "Grunnlag MVA innførsel av varer, middels sats"),
                new StandardAccount(4383, "Grunnlag MVA innførsel av varer, middels sats, motkonto"),
                new StandardAccount(4384, "Grunnlag innførsel av varer med nullsats"),
                new StandardAccount(4385, "Grunnlag innførsel av varer med nullsats, motkonto"),
                new StandardAccount(4386, "Innenlands kjøp av varer, omvendt avgiftsplikt"),
                new StandardAccount(4387, "Innenlands kjøp av varer, omvendt avgiftsplikt, motkonto"),
                new StandardAccount(4390, "Beholdningsendring"),
                new StandardAccount(4500, "Fremmedytelse og underentreprise"),
                new StandardAccount(4550, "Fremmedytelse og underentreprise, opplysningspliktig"),
                new StandardAccount(4590, "Beholdningsendring"),
                new StandardAccount(4600, "Emballasjematerialer "),
                new StandardAccount(4690, "Beholdningsendring"),
                new StandardAccount(4900, "Annen periodisering"),
                new StandardAccount(4990, "Beholdningsendring, egentilvirkede anleggsmidler"),
                new StandardAccount(5000, "Lønn til ansatte"),
                new StandardAccount(5005, "Avtalte tariffgodtgjørelser"),
                new StandardAccount(5090, "Påløpt, ikke utbetalt lønn"),
                new StandardAccount(5092, "Feriepenger"),
                new StandardAccount(5099, "Andre lønnsposteringer"),
                new StandardAccount(5200, "Fri bil"),
                new StandardAccount(5210, "Fri telefon"),
                new StandardAccount(5220, "Fri avis"),
                new StandardAccount(5230, "Fri kost"),
                new StandardAccount(5235, "Fri losji"),
                new StandardAccount(5236, "Fri bolig"),
                new StandardAccount(5240, "Rentefordel"),
                new StandardAccount(5250, "Gruppelivsforsikring"),
                new StandardAccount(5252, "Ulykkesforsikring"),
                new StandardAccount(5253, "Personavbruddsforsikring"),
                new StandardAccount(5254, "Yrkesskadeforsikring, skattepliktig del"),
                new StandardAccount(5255, "Tilskudd og premie til pensjonsordning, arbeidsgiveravgiftspliktig"),
                new StandardAccount(5280, "Annen fordel i arbeidsforhold"),
                new StandardAccount(5290, "Motkonto for gruppe 52"),
                new StandardAccount(5330, "Godtgjørelse til styremedlemmer"),
                new StandardAccount(5335, "Godtgjørelse til medlemmer av bedriftsforsamlingen"),
                new StandardAccount(5390, "Annen opplysningspliktig godtgjørelse"),
                new StandardAccount(5400, "Arbeidsgiveravgift "),
                new StandardAccount(5404, "Påløpt arbeidsgiveravgift påløpt lønn"),
                new StandardAccount(5405, "Arbeidsgiveravgift av påløpte feriepenger "),
                new StandardAccount(5406, "Påløpt arbeidsgiveravgift av påløpte andre honorarer"),
                new StandardAccount(5420, "Innberetningspliktig pensjonskostnad utbetalt over drift"),
                new StandardAccount(5430, "Finansskatt av lønn"),
                new StandardAccount(5431, "Finansskatt av påløpte feriepenger"),
                new StandardAccount(5434, "Påløpt finansskatt påløpt lønn"),
                new StandardAccount(5435, "Påløpt finansskatt påløpte feriepenger"),
                new StandardAccount(5436, "Påløpt finansskatt påløpte andre honorarer"),
                new StandardAccount(5500, "Annen kostnadsgodtgjørelse "),
                new StandardAccount(5600, "Arbeidsgodtgjørelse til eiere i DLS"),
                new StandardAccount(5700, "Lærlingtilskudd"),
                new StandardAccount(5750, "Annet lønnstilskudd"),
                new StandardAccount(5800, "Refusjon av sykepenger"),
                new StandardAccount(5820, "Refusjon av arbeidsgiveravgift"),
                new StandardAccount(5830, "Refusjon arbeidsmarkedstiltak"),
                new StandardAccount(5890, "Annen refusjon"),
                new StandardAccount(5899, "Motkonto for gruppe 58"),
                new StandardAccount(5900, "Gaver til ansatte, fradragsberettiget"),
                new StandardAccount(5905, "Gaver til ansatte, ikke fradragsberettiget"),
                new StandardAccount(5910, "Kantinekostnad"),
                new StandardAccount(5915, "Overtidsmat"),
                new StandardAccount(5919, "Trekk kantinekostnader ansatte"),
                new StandardAccount(5920, "Yrkesskadeforsikring"),
                new StandardAccount(5930, "Annen ikke arbeidsgiveravgiftspliktig forsikring"),
                new StandardAccount(5941, "LO/NHO-ordningen (O&U + sluttvederlag)"),
                new StandardAccount(5942, "LO/NHO-ordningen (AFP)"),
                new StandardAccount(5950, "Obligatorisk tjenestepensjon (OTP)"),
                new StandardAccount(5990, "Annen personalkostnad"),
                new StandardAccount(5999, "Motkonto for gruppe 59"),
                new StandardAccount(6000, "Avskrivning på bygninger og annen fast eiendom"),
                new StandardAccount(6010, "Avskrivning på transportmidler"),
                new StandardAccount(6015, "Avskrivning på maskiner"),
                new StandardAccount(6017, "Avskrivning på inventar"),
                new StandardAccount(6020, "Avskrivning på ervervet goodwill"),
                new StandardAccount(6029, "Avskrivning på andre immaterielle eiendeler"),
                new StandardAccount(6050, "Nedskrivning av varige driftsmidler"),
                new StandardAccount(6055, "Nedskrivning av immaterielle eiendeler"),
                new StandardAccount(6059, "Reversering av nedskrivning varige driftsmidler og immaterielle eiendeler"),
                new StandardAccount(6100, "Frakt, transportkostnad og forsikring ved vareforsendelse"),
                new StandardAccount(6110, "Toll og spedisjonskostnad ved vareforsendelse"),
                new StandardAccount(6190, "Annen frakt- og transportkostnad ved salg"),
                new StandardAccount(6200, "Elektrisitet"),
                new StandardAccount(6210, "Gass"),
                new StandardAccount(6220, "Fyringsolje"),
                new StandardAccount(6230, "Kull, koks"),
                new StandardAccount(6240, "Ved"),
                new StandardAccount(6250, "Bensin, dieselolje"),
                new StandardAccount(6260, "Vann"),
                new StandardAccount(6290, "Annet brensel"),
                new StandardAccount(6300, "Leie lokale"),
                new StandardAccount(6320, "Renovasjon, vann, avløp o.l. "),
                new StandardAccount(6340, "Lys"),
                new StandardAccount(6345, "Varme"),
                new StandardAccount(6360, "Renhold"),
                new StandardAccount(6391, "Felles-/administrasjonskostnad senterforening"),
                new StandardAccount(6399, "Annen kostnad lokaler"),
                new StandardAccount(6400, "Leie maskiner"),
                new StandardAccount(6410, "Leie inventar"),
                new StandardAccount(6420, "Leie datasystemer"),
                new StandardAccount(6430, "Leie andre kontormaskiner"),
                new StandardAccount(6440, "Leie transportmidler"),
                new StandardAccount(6490, "Annen leiekostnad"),
                new StandardAccount(6500, "Motordrevet verktøy"),
                new StandardAccount(6510, "Håndverktøy"),
                new StandardAccount(6520, "Hjelpeverktøy"),
                new StandardAccount(6530, "Spesialverktøy"),
                new StandardAccount(6540, "Inventar"),
                new StandardAccount(6551, "Datautstyr"),
                new StandardAccount(6552, "Programvare anskaffelse"),
                new StandardAccount(6553, "Programvare årlig vedlikehold"),
                new StandardAccount(6560, "Rekvisita"),
                new StandardAccount(6570, "Arbeidsklær, opplysningspliktig"),
                new StandardAccount(6571, "Arbeidsklær, ikke opplysningspliktig"),
                new StandardAccount(6575, "Verneutstyr"),
                new StandardAccount(6590, "Annet driftsmateriale"),
                new StandardAccount(6600, "Reparasjon og vedlikehold bygninger"),
                new StandardAccount(6620, "Reparasjon og vedlikehold utstyr "),
                new StandardAccount(6690, "Reparasjon og vedlikehold annet"),
                new StandardAccount(6700, "Revisjonshonorar"),
                new StandardAccount(6702, "Honorar annen bistand fra revisor"),
                new StandardAccount(6705, "Regnskapshonorar"),
                new StandardAccount(6706, "Honorarer annen bistand fra regnskapsfører"),
                new StandardAccount(6720, "Honorar for annen økonomisk rådgivning"),
                new StandardAccount(6725, "Honorar for juridisk bistand, fradragsberettiget"),
                new StandardAccount(6726, "Honorar for juridisk bistand, ikke fradragsberettiget"),
                new StandardAccount(6750, "Honorar for databistand"),
                new StandardAccount(6790, "Annen fremmed tjeneste, opplysningspliktig"),
                new StandardAccount(6795, "Annen fremmed tjeneste, ikke opplysningspliktig"),
                new StandardAccount(6800, "Kontorrekvisita"),
                new StandardAccount(6820, "Trykksak"),
                new StandardAccount(6840, "Aviser, tidsskrifter, bøker o.l. "),
                new StandardAccount(6860, "Møte, kurs, oppdatering o.l. "),
                new StandardAccount(6890, "Annen kontorkostnad"),
                new StandardAccount(6900, "Telefon"),
                new StandardAccount(6903, "Mobiltelefon "),
                new StandardAccount(6907, "Datakommunikasjon"),
                new StandardAccount(6909, "Annen telekommunikasjon"),
                new StandardAccount(6940, "Porto"),
                new StandardAccount(7000, "Drivstoff transportmiddel 1"),
                new StandardAccount(7020, "Vedlikehold transportmiddel 1"),
                new StandardAccount(7040, "Forsikring transportmiddel 1"),
                new StandardAccount(7090, "Annen kostnad transportmiddel 1"),
                new StandardAccount(7100, "Bilgodtgjørelse, opplysningspliktig"),
                new StandardAccount(7130, "Reisekostnad, opplysningspliktig"),
                new StandardAccount(7140, "Reisekostnad, ikke opplysningspliktig"),
                new StandardAccount(7150, "Diettkostnad, opplysningspliktig"),
                new StandardAccount(7160, "Diettkostnad, ikke opplysningspliktig"),
                new StandardAccount(7190, "Verktøygodtgjørelse"),
                new StandardAccount(7195, "Arbeidstøygodtgjørelse"),
                new StandardAccount(7199, "Annen kostnadsgodtgjørelse"),
                new StandardAccount(7200, "Provisjonskostnad, opplysningspliktig"),
                new StandardAccount(7210, "Provisjonskostnad, ikke opplysningspliktig"),
                new StandardAccount(7300, "Salgskostnad"),
                new StandardAccount(7320, "Reklameannonser"),
                new StandardAccount(7322, "Reklameavis/-katalog mv."),
                new StandardAccount(7323, "Reklameartikler"),
                new StandardAccount(7329, "Annen reklamekostnad"),
                new StandardAccount(7350, "Representasjon, fradragsberettiget"),
                new StandardAccount(7360, "Representasjon, ikke fradragsberettiget"),
                new StandardAccount(7390, "Annen salgskostnad, fradragsberettiget"),
                new StandardAccount(7395, "Annen salgskostnad, ikke fradragsberettiget"),
                new StandardAccount(7400, "Kontingent, fradragsberettiget"),
                new StandardAccount(7410, "Kontingent, ikke fradragsberettiget"),
                new StandardAccount(7420, "Gave, fradragsberettiget"),
                new StandardAccount(7430, "Gave, ikke fradragsberettiget"),
                new StandardAccount(7500, "Forsikringspremie"),
                new StandardAccount(7530, "Frivillig tilleggstrygd for næringsdrivende"),
                new StandardAccount(7550, "Garantikostnad"),
                new StandardAccount(7560, "Servicekostnad"),
                new StandardAccount(7600, "Lisensavgift"),
                new StandardAccount(7605, "Royalties"),
                new StandardAccount(7610, "Patentkostnad ved egen patent"),
                new StandardAccount(7620, "Kostnad ved varemerke o.l. "),
                new StandardAccount(7630, "Kontroll-, prøve- og stempelavgifter"),
                new StandardAccount(7710, "Styremøter"),
                new StandardAccount(7715, "Bedriftsforsamlingsmøter"),
                new StandardAccount(7720, "Generalforsamling"),
                new StandardAccount(7730, "Kostnad ved egne aksjer"),
                new StandardAccount(7750, "Eiendoms- og festeavgift"),
                new StandardAccount(7770, "Bank- og kortgebyr"),
                new StandardAccount(7775, "Kredittkortprovisjoner"),
                new StandardAccount(7780, "Grunnlag MVA innførsel av varer, høy sats"),
                new StandardAccount(7781, "Grunnlag MVA innførsel av varer, høy sats, motkonto"),
                new StandardAccount(7782, "Grunnlag MVA innførsel av varer, middels sats"),
                new StandardAccount(7783, "Grunnlag MVA innførsel av varer, middels sats, motkonto"),
                new StandardAccount(7784, "Grunnlag innførsel av varer med null sats"),
                new StandardAccount(7785, "Grunnlag innførsel av varer med  null sats, motkonto"),
                new StandardAccount(7786, "Grunnlag utgående MVA kjøp tjenester fra utlandet "),
                new StandardAccount(7787, "Grunnlag utgående MVA kjøp tjenester fra utlandet, motkonto"),
                new StandardAccount(7788, "Innenlands kjøp av varer og tjenester, omvendt avgiftsplikt"),
                new StandardAccount(7789, "Innenlands kjøp av varer og tjenester, omvendt avgiftsplikt, motkonto"),
                new StandardAccount(7798, "Annen kostnad, fradragsberettiget"),
                new StandardAccount(7799, "Annen kostnad, ikke fradragsberettiget"),
                new StandardAccount(7820, "Innkommet på tidligere nedskrevne fordringer, skattepliktig"),
                new StandardAccount(7825, "Innkommet på tidligere nedskrevne fordringer, ikke skattepliktig"),
                new StandardAccount(7830, "Tap på fordringer, fradragsberettiget"),
                new StandardAccount(7835, "Tap på fordringer, ikke fradragsberettiget"),
                new StandardAccount(7839, "Endring i avsetning for forventet tap"),
                new StandardAccount(7860, "Tap på kontrakter"),
                new StandardAccount(7881, "Salgssum immatr. eiendeler og varige driftsmidler, avgiftspliktig salg"),
                new StandardAccount(7882, "Salgssum immatr. eiendeler og varige driftsmidler, avgiftsfritt salg"),
                new StandardAccount(7889, "Motkonto, balanseverdi solgte immatr. eiendeler og varige driftsmidler"),
                new StandardAccount(7891, "Salgssum finansielle anleggsmidler"),
                new StandardAccount(7899, "Motkonto balanseført verdi solgte finansielle driftsmidler"),
                new StandardAccount(7971, "Justering inngående merverdiavgift fast eiendom"),
                new StandardAccount(7972, "Justering inngående merverdiavgift maskiner, inventar mv"),
                new StandardAccount(8000, "Aksjeutbytte fra norsk datterselskap"),
                new StandardAccount(8003, "Aksjeutbytte fra utenlandsk datterselskap, innenfor fritaksmetoden"),
                new StandardAccount(8004, "Aksjeutbytte fra utenlandsk datterselskap, utenfor fritaksmetoden"),
                new StandardAccount(8005, "Resultatandel fra datterselskap etter egenkapitalmetoden"),
                new StandardAccount(8007, "Gevinst/tap ved realisasjon av aksjer/andeler i datterselskap, innenfor fritaksmetoden"),
                new StandardAccount(8008, "Gevinst/tap ved realisasjon av aksjer/andeler i datterselskap, utenfor fritaksmetoden"),
                new StandardAccount(8010, "Aksjeutbytte fra norsk foretak i samme konsern"),
                new StandardAccount(8013, "Aksjeutbytte fra utenlandsk foretak i samme konsern, innenfor fritaksmetoden"),
                new StandardAccount(8014, "Aksjeutbytte fra utenlandsk foretak i samme konsern, utenfor fritaksmetoden"),
                new StandardAccount(8017, "Gevinst/tap ved realisasjon av aksjer/andeler i foretak i samme konsern, innenfor fritaksmodellen"),
                new StandardAccount(8018, "Gevinst/tap ved realisasjon av aksjer/andeler i foretak i samme konsern, utenfor fritaksmetoden"),
                new StandardAccount(8020, "Aksjeutbytte fra norsk tilknyttet selskap"),
                new StandardAccount(8023, "Aksjeutbytte fra utenlandsk tilknyttet selskap, innenfor fritaksmetoden"),
                new StandardAccount(8024, "Aksjeutbytte fra utenlandsk tilknyttet selskap, utenfor fritaksmetoden"),
                new StandardAccount(8025, "Resultatandel fra tilknyttet selskap etter egenkapitalmetoden"),
                new StandardAccount(8027, "Gevinst/tap ved realisasjon av aksjer/andeler i tilknyttet selskap, innenfor fritaksmetoden"),
                new StandardAccount(8028, "Gevinst/tap ved realisasjon av aksjer/andeler i tilknyttet selskap, utenfor fritaksmetoden"),
                new StandardAccount(8030, "Renteinntekt fra foretak i samme konsern"),
                new StandardAccount(8040, "Renteinntekt, skattefri"),
                new StandardAccount(8050, "Renteinntekt bankinnskudd"),
                new StandardAccount(8055, "Renteinntekt kundefordringer"),
                new StandardAccount(8059, "Annen renteinntekt"),
                new StandardAccount(8060, "Valutagevinst (agio)"),
                new StandardAccount(8070, "Aksjeutbytte fra norsk foretak"),
                new StandardAccount(8073, "Aksjeutbytte fra utenlandsk foretak, innenfor fritaksmetoden"),
                new StandardAccount(8074, "Aksjeutbytte fra utenlandsk foretak, utenfor fritaksmetoden"),
                new StandardAccount(8077, "Gevinst ved realisasjon av andre aksjer/andeler, innenfor fritaksmetoden"),
                new StandardAccount(8078, "Gevinst ved realisasjon av andre aksjer/andeler, utenfor fritaksmetoden"),
                new StandardAccount(8079, "Annen finansinntekt"),
                new StandardAccount(8080, "Verdiøkning av finansielle instrumenter vurdert til virkelig verdi, urealisert"),
                new StandardAccount(8082, "Verdiøkning av finansielle instrumenter vurdert til virkelig verdi realisert"),
                new StandardAccount(8090, "Inntekt på andre investeringer"),
                new StandardAccount(8100, "Verdireduksjon av finansielle instrumenter vurdert til virkelig verdi, urealisert"),
                new StandardAccount(8105, "Verdireduksjon av finansielle instrumenter vurdert til virkelig verdi, realisert"),
                new StandardAccount(8110, "Nedskrivning av andre finansielle omløpsmidler"),
                new StandardAccount(8120, "Nedskrivning av finansielle anleggsmidler"),
                new StandardAccount(8129, "Reversering av nedskrivning finansielle anleggsmidler"),
                new StandardAccount(8130, "Rentekostnad til foretak i samme konsern"),
                new StandardAccount(8140, "Rentekostnad, ikke fradragsberettiget"),
                new StandardAccount(8150, "Rentekostnad banklån"),
                new StandardAccount(8154, "Renter/provisjon kassekreditt"),
                new StandardAccount(8155, "Rentekostnad leverandørgjeld"),
                new StandardAccount(8159, "Annen rentekostnad"),
                new StandardAccount(8160, "Valutatap (disagio)"),
                new StandardAccount(8177, "Tap ved realisasjon av aksjer/andeler, innenfor fritaksmetoden (jf. konto 8007, 8017 og 8027)"),
                new StandardAccount(8178, "Tap ved realisasjon av aksjer/andeler, utenfor fritaksmetoden (jf. konto 8008, 8018 og 8028)"),
                new StandardAccount(8179, "Annen finanskostnad"),
                new StandardAccount(8300, "Betalbar skatt"),
                new StandardAccount(8309, "Betalbar skatt, for mye/lite avsatt tidligere år"),
                new StandardAccount(8320, "Endring i utsatt skatt/skattefordel"),
                new StandardAccount(8400, "Virkning av prinsippendring"),
                new StandardAccount(8410, "Korrigering av feil"),
                new StandardAccount(8500, "Virkning av prinsippendring"),
                new StandardAccount(8510, "Korrigering av feil"),
                new StandardAccount(8600, "Betalbar skatt, virkning av prinsippendring"),
                new StandardAccount(8602, "Betalbar skatt, korrigering av feil"),
                new StandardAccount(8609, "Betalbar skatt, for mye/lite avsatt tidligere år"),
                new StandardAccount(8620, "Endring utsatt skatt/skattefordel, virkning av prinsippendring"),
                new StandardAccount(8622, "Endring utsatt skatt/skattefordel, korrigering av feil"),
                new StandardAccount(8800, "Årsresultat"),
                new StandardAccount(8900, "Overføringer fond "),
                new StandardAccount(8910, "Overføringer felleseid andelskapital for samvirkeforetak"),
                new StandardAccount(8920, "Avsatt utbytte / renter på egenkapitalbevis / etterbetaling for samvirkeforetak"),
                new StandardAccount(8921, "Avsatt tilleggsutbytte"),
                new StandardAccount(8922, "Avsatt ekstraordinær utbytte"),
                new StandardAccount(8930, "Mottatt konsernbidrag"),
                new StandardAccount(8935, "Avsatt konsernbidrag"),
                new StandardAccount(8950, "Fondsemisjon"),
                new StandardAccount(8960, "Overføringer annen egenkapital"),
                new StandardAccount(8968, "Overføringer udisponert vinning"),
                new StandardAccount(8969, "Overføringer udisponert tap"),
                new StandardAccount(8980, "Privatuttak"),
                new StandardAccount(8990, "Udekket tap")
            };

    /// <summary>
    /// Get a StandardAccount based on AccountID
    /// </summary>
    /// <param name="accountId">AccountID of the StandardAccount to get</param>
    /// <returns>Returns a StandardAccount according to accountId</returns>
    public static StandardAccount Get(int accountId)
    {
        return standardAccounts.SingleOrDefault((elem) => { return elem.AccountID == accountId; });
    }

    /// <summary>
    /// Get a StandardAccount based on AccountID
    /// </summary>
    /// <param name="accountId">AccountID of the StandardAccount to get</param>
    /// <returns>Returns a <c>StandardAccount</c></returns>
    public static StandardAccount Get(string accountId)
    {
        return standardAccounts.SingleOrDefault((elem) => { return elem.AccountIDStr.Equals(accountId); });
    }

    /// <summary>
    /// Search for string in <c>StandardAccount.Description</c>
    /// </summary>
    /// <param name="searchString">This is the string that will searched for</param>
    /// <returns>Returns a Array of <c>StandardAccount</c></returns>
    public static IEnumerable<StandardAccount> Search(string searchString)
    {
        return standardAccounts.Where((elem) => { return elem.Description.Contains(searchString); });
    }
}
